---
title: "July 2018 Metrics as of 26th"
author: "Jeff Anderson"
date: "July 27, 2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r message=FALSE, echo=FALSE }
options(max.print = 400, warn=-1)

library(dplyr)
library(lubridate)
library(ggplot2)



machines = read.table("agents.csv", sep=",")
colnames(machines) = c("machine", "opsys")
bad.runs = read.table("cmdfails.csv", sep=",")
colnames(bad.runs) = 
  c("job.name", "job.group", "sn.assignment","machine", "joid",
    "run.num","try.number","start.epoc","start.date", "end.epoc",
    "end.date","seconds.ran","status", "exit.code", "incident",
    "process.date")
bad.runs = inner_join(bad.runs, machines)
bad.runs = bad.runs %>%
  mutate(
    end.month = factor(substr(end.date,1,7)),
    end.dom = factor(substr(end.date,1,10)),
    end.day = factor(substr(end.date,9,10)),
    end.hour = factor(substr(end.date,12,13)),
    end.wday = factor(wday(end.date, label=T))
  )

term.runs = bad.runs %>% filter(status == "TERMINATED")
fail.runs = bad.runs %>% filter(status == "FAILURE")

mon.fails = fail.runs %>%
  filter(as.character(end.month) >= "2018-07" & job.group != "EST") 

prior.fails = mon.fails %>%
  filter(end.day == '26')

fails.job = mon.fails %>%
  select(job.name) %>%
  group_by(job.name) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

prior.fails.job = prior.fails %>%
  select(job.name) %>%
  group_by(job.name) %>%
  summarize(total.fails = n()) %>%
  arrange(desc(total.fails))

fails.machine = mon.fails %>%
  select(machine) %>%
  group_by(machine) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

fails.code = mon.fails %>%
  select(exit.code) %>%
  group_by(exit.code) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

fails.hour = mon.fails %>%
  select(end.hour) %>%
  group_by(end.hour) %>%
  summarize(total.fails = n()) %>%
  arrange(end.hour)

fails.wday.hour = mon.fails %>%
  select(end.wday, end.hour) %>%
  group_by(end.wday, end.hour) %>%
  summarize(total.fails = n())

fails.opsys = mon.fails %>%
  select(opsys) %>%
  group_by(opsys) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

fails.group = mon.fails %>%
  select(job.group) %>%
  group_by(job.group) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

fails.group.day = mon.fails %>%
  select(end.dom, job.group) %>%
  group_by(end.dom, job.group) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 10) %>%
  arrange(desc(total.fails))

fails.pior.group = prior.fails %>%
  select(job.group) %>%
  group_by(job.group) %>%
  summarize(total.fails = n()) %>%
  filter(total.fails > 2) %>%
  arrange(desc(total.fails))
```

# ****************************
# Month to Date Failure Info
# ****************************

# Job Failure Counts by Job

```{r echo=FALSE}
print(fails.job)
```

## Total Failures by Job Group

```{r echo=FALSE}
group.monthly.totals = ggplot(fails.group, aes(job.group, total.fails, fill=job.group))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Monthly Totals Per Group")
print(group.monthly.totals)
```

## Failures by Day by Group

```{r echo=FALSE}
daily.totals.by.group = 
  ggplot(fails.group.day, aes(end.dom, total.fails, fill=job.group))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Daily Totals Per Group")
print(daily.totals.by.group)
```

## Failures by Machine

```{r echo=FALSE}
totals.by.machine = 
  ggplot(fails.machine, aes(machine, total.fails, fill=machine))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Failures By Machine")
print(totals.by.machine)
```


## Failures by Exit Code

```{r echo=FALSE}
print(fails.code)
```

## Total Failures by Operating System

```{r echo=FALSE}
opsys.totals = ggplot(fails.opsys, aes(opsys, total.fails, fill=opsys))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Monthly Totals Per OpSys")
print(opsys.totals)
```

## Total Failures by Hour of Day

```{r echo=FALSE}
hourly.totals = ggplot(fails.hour, aes(end.hour, total.fails, fill=end.hour))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Monthly Totals Per Hour of Day")
print(hourly.totals)
```

## Total Failures by Day of Week / Hour

```{r echo=FALSE}
wday.hour.totals = ggplot(fails.wday.hour, aes(end.wday, total.fails, fill=end.hour))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Monthly Totals Per Day / Hour")
print(wday.hour.totals)
```


# ****************************
# Yesterday Information
# ****************************

## Yesterday Failures by Job

```{r echo=FALSE}
print(prior.fails.job)
```

## Yesterday Failures by Group

```{r echo=FALSE}
prior.totals.by.group = 
  ggplot(fails.pior.group, aes(job.group, total.fails, fill=job.group))+
  geom_col()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  labs(title="Prior Day Failure Totals Per Group")
print(prior.totals.by.group)

```